### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by rent4ever** [rickkas7/LIS3DH#2]
Not an issue, I just don't know how to leave a comment.  I wanted to start out by saying thank you, thank you, thank you.  I just have one question.  It works perfectly, but only if the AssetTracker is in a flat position.  Is that just the nature of the Accelerometer or is this an initialization issue and something that can be easily done.

Regards,
Bill Freeman

**Comment by rickkas7** [comment]
You're welcome! It's probably because of this line of code in LIS3DH.cpp

int1_cfg = INT1_CFG_YHIE_YUPE | INT1_CFG_XHIE_XUPE;

I couldn't get it to reliably cancel out the force of gravity, so I just turned off the Z axis. If you have it in any other orientation, of course gravity is now applying force in X and Y directions.

The chip should be able to cancel it out, but I couldn't get it to work. Thought I didn't spend that much time trying.

**Comment by DigiDr** [comment]
This is a problem for me too! I've tried setting adding the Z axis in int1_cfg: indeed, it seems as written, the gravity isn't being cancelled properly.

**Comment by DigiDr** [comment]
OK, so with some fiddling:

writeRegister8(REG_CTRL_REG2, CTRL_REG2_HPM1 | CTRL_REG2_HPM0 | CTRL_REG2_HPIS1);

& adding the Z axis to int1_cfg

Seems to give desired results, though i couldn't tell you why (the documentation needs work!)

**Comment by rickkas7** [comment]
That seems logical. I figured you'd either need to enable the high pass filter or set a reference level. The high pass filter is preferable because if you have to set a reference level you also need to figure out when it's not currently moving because you should only set the reference when stationary. I'd definitely go with the high-pass filter if it works!

**Comment by DigiDr** [comment]
@rickkas7 noticed Z axis hasn't been added to your new code. Is it now safe to do so? Haven't had a chance to go through

Merry X-mas and thanks for your work on the new libraries.

**Comment by rickkas7** [comment]
There's Z-axis and correct support for gravity compensation in the LIS3DH code I put in:

https://github.com/rickkas7/AssetTrackerRK

I should merge the code back into this, but I have not done so yet. It should just drop right in.

**Comment by DigiDr** [comment]
Oh right! I still see "int1_cfg = LIS3DH::INT1_CFG_YHIE_YUPE | LIS3DH::INT1_CFG_XHIE_XUPE;"  (No Z axis?) in the LIS3DH.cpp from the RK codebase?

Am i looking in the wrong place? The LI3DH files are identical, no?

**Comment by rickkas7** [comment]
I'm pretty sure it was an oversight not adding it to line 27. I think it should be:

```
int1_cfg = LIS3DH::INT1_CFG_ZHIE_ZUPE | LIS3DH::INT1_CFG_YHIE_YUPE | LIS3DH::INT1_CFG_XHIE_XUPE;
```

I gave it a quick test with the wake on move test and it works properly for me.

**Comment by DigiDr** [comment]
That makes sense to me!

You also set int1_cfg at line 50 - but i gather that is for an entirely separate purpose. 

I will retest everything with the modified line 27 and report back.

**Comment by rickkas7** [comment]
Closing since there hasn't been any activity, feel free to reopen if necessary.
